### ISSUE TITLE
I can't install anything

### ISSUE THREAD

**Issue by Stu75e** [nix-community/nix-on-droid#279]
When installing any program in the terminal, only the terminal stops

Version 0.118.0_v0.3.3_nix

**Comment by t184256** [comment]
I'm not sure I understand what does "terminal stops" mean. Could you leave more details, provide logs/screenshots, specify expectations? Ideally, all of the above.

**Comment by Stu75e** [comment]
I try to install a program such as "man" in the terminal, but the program does not respond and then stops

**Comment by t184256** [comment]
"Stops" as in "you're looking at a terminal prompt again"? "Stops" as in "the whole app crashes and now you're in a different app"? Is there any output in any form? Can you copy-paste text if any? Make a screenshot and post it here? Finally, what were you inputting to make it happen? It's nearly impossible to give a meaningful answer without all of that information provided.

**Comment by Stu75e** [comment]
Unfortunately, no matter what I try, I can't find the problem again, so I'll close this topic for now.  I will let you know if I ever encounter the same problem.  Thank you.
