### ISSUE TITLE
Warn to use `nix-on-droid switch --flake`

### ISSUE THREAD

**Issue by t184256** [nix-community/nix-on-droid#295]
If one has a `~/.config/nix-on-droid/flake.nix`, likely from bootstrapping with flakes, and attempts to `nix-on-droid switch` without the `--flake` switch, we should print a `warning: you have a flake.nix, you probably meant to run nix-on-droid-switch --flake .config/nix-on-droid`.

**Comment by b-rodrigues** [comment]
I agree, just installed nix-on-droid with flakes enabled but nix-on-droid switch was not returning an useful error message. This would be a great addition!
