### ISSUE TITLE
Failure to build `fcitx-engines is deprecated`

### ISSUE THREAD

**Issue by RyanGibb** [nix-community/nix-on-droid#298]
```
nix-on-droid switch --flake github:RyanGibb/nixos/5896ce
Building activation package...
error: fcitx-engines is deprecated, please use fcitx5 instead.
(use '--show-trace' to show detailed location information)
```

Though I'm not using `fcitx` as far as I can tell:
- https://github.com/RyanGibb/nixos/blob/5896cecad7848495d3876795752c1ebf3de61bcc/nix-on-droid/default.nix
- https://github.com/RyanGibb/nixos/blob/5896cecad7848495d3876795752c1ebf3de61bcc/flake.nix#L170

**Comment by Gerschtli** [comment]
```
nix why-depends github:RyanGibb/nixos\#nixOnDroidConfigurations.default.activationPackage github:RyanGibb/nixos\#nixOnDroidConfigurations.default.activationPackage --show-trace
```
See output here http://ix.io/4J3W

Looks like it is caused by nmd that is used to generate the man pages.

It works when you use an up to date version of home-manager.

```nix
nix-on-droid.inputs.home-manager.follows = "home-manager";
```

**Comment by RyanGibb** [comment]
Thanks @Gerschtli!
