### ISSUE TITLE
Crashed at launch

### ISSUE THREAD

**Issue by Unknown78** [nix-community/nix-on-droid#306]
App Version: [0.118.0_v0.3.3_nix (188033)](https://f-droid.org/packages/com.termux.nix/)
OS Version: Android Nougat 7.1.1 (API 25)

Device: Samsung Galaxy Note 4 SM-N910H
Architecture: armeabi-v7a
System: 
- [REFINED_NOTE8_7.1_T2.zip](https://t.me/RefinedNougat/491)
- [Konup_RisingNote4_for_RefinedNote8_7.1.1_ver.2.3.zip](https://xdaforums.com/t/refined-note-8-7-1-1-exynos-updated-mod-risingnote4-ver-2-3.4363583/) 
- [Konup_HomeOneUI_RefinedNote8_7.1.1_ver.2.0_14.07.2022.zip](https://xdaforums.com/t/refined-note-8-7-1-1-exynos-oneui-port-home-screen-bixby-weather-wallpaper-choice-apps.4371353/)
- [Konup_SamsungCamera7_RefinedNote8_7.1.1_v.1.2.zip](https://xdaforums.com/t/refined-note-8-7-1-1-exynos-updated-stock-samsungcamera7-ver-1-2-now-writing-60fps.4201475/)

Boot:
- [Helios_Kernel-V3.1-N910C.H-20200809.img](https://t.me/RefinedNougat/493)
- Magisk debug [26401_cfb20b0](https://github.com/topjohnwu/Magisk/actions/runs/6820908782)

### Log
[Nix-on-Droid_0.118.0_v0.3.3_nix_logcat_2023-11-26T07.41.51.log](https://github.com/nix-community/nix-on-droid/files/13465592/Nix-on-Droid_0.118.0_v0.3.3_nix_logcat_2023-11-26T07.41.51.log)

Some highlights:
```java
--------- beginning of crash
11-26 07:41:58.098  7134  7134 E AndroidRuntime: FATAL EXCEPTION: main
11-26 07:41:58.098  7134  7134 E AndroidRuntime: Process: com.termux.nix, PID: 7134
11-26 07:41:58.098  7134  7134 E AndroidRuntime: android.app.RemoteServiceException: Bad notification posted from package com.termux.nix: Couldn't expand RemoteViews for: StatusBarNotification(pkg=com.termux.nix user=UserHandle{0} id=1 tag=null key=0|com.termux.nix|1|null|10363: Notification(pri=1 contentView=null vibrate=default sound=null defaults=0x2 flags=0x10 color=0xff607d8b vis=PRIVATE semFlags=0x0 semPriority=0))
```

**Comment by t184256** [comment]
On November 26, 2023 1:50:04 AM GMT+01:00, Unknown78 ***@***.***> wrote:
>Architecture: armeabi-v7a
32-bit devices are not supported, how have you even bootstrapped? There's no 32-bit tarball.

**Comment by Unknown78** [comment]
This is the first launch menu:
```
Bootstrap zipball location
Enter the URL of a directory containing bootstrap-arm.zip

https://nix-on-droid.unboiled.info/bootstrap-release-23.05
OK
```

<hr>

This is on readme
> It also used to compile for i686 devices, but the developers don't own any and nobody has reported whether it actually worked or not, so it's no longer built unless a user shows up. Sorry, it would not work on 32-bit ARM devices and it's not an easy feat to pull off.


This is on F-Droid

> Version 0.118.0_v0.3.3_nix (188033) suggested Added on 2023-07-27
> arm64-v8a armeabi-v7a x86 x86_64
> 
> This version requires Android 5.0 or newer.


The readme says would not work on 32-bit but yet F-Droid has 32-bit release.
I don't see 64-bit letter on that link there.
Only after I open the link at this moment that there's no 32-bit to begin with.
What a big misunderstanding I've had.

**Comment by t184256** [comment]
> Enter the URL of a directory containing bootstrap-arm.zip
> https://nix-on-droid.unboiled.info/bootstrap-release-23.05
> OK

But there's no bootstrap-arm.zip there. I have no idea how has this worked.

> This is on F-Droid
> arm64-v8a armeabi-v7a x86 x86_64

Thanks for reporting, I should fix that.

**Comment by Unknown78** [comment]
I guess the textbox has default value for the link of the latest bootstrap.
You could analyze the logcat that I give, it probably didn't download anything, as I see it the loading just ends very fast.

I hope by fixing you mean uploading the `bootstrap-arm.zip` in there, haha.
