### ISSUE TITLE
Bash 5.2

### ISSUE THREAD

**Issue by Truly93** [nix-community/nix-on-droid#317]
Is all it keeps reading when I run the app

**Comment by Gerschtli** [comment]
What did you do after downloading the app until you got to this message? Please also provide a screenshot.

**Comment by ASMARARAIN** [comment]
![Screenshot_2024-06-02-14-06-19-22_7c9fdf2472f91e6d21f35bb801178e75](https://github.com/nix-community/nix-on-droid/assets/171451079/0fdc9c18-0071-45ae-a6d0-41960d770a47)

**Comment by Gerschtli** [comment]
That is just the shell, if that pops up, you are ready to go :)
