### ISSUE TITLE
How to remove welcome message

### ISSUE THREAD

**Issue by Greenarrow4245** [nix-community/nix-on-droid#318]
Welcome to Nix-on-Droid!
If nothing works, open an issue at https://github.com/t184256/nix-on-droid/issues or try the rescue shell.

This one

**Comment by Gerschtli** [comment]
`environment.motd = null` is what you are looking for :)

**Comment by Greenarrow4245** [comment]
> `environment.motd = null` is what you are looking for :)

Where it is I'm kinda new to the nix file system

**Comment by Gerschtli** [comment]
You need to set it in your ~/.config/nixpkgs/nix-on-droid.nix config file and apply it with `nix-on-droid switch`

**Comment by t184256** [comment]
Answered above.
