### ISSUE TITLE
23.11 Release

### ISSUE THREAD

**Issue by storopoli** [nix-community/nix-on-droid#321]
We need to have a 23.11 release.

**Comment by t184256** [comment]
On January 17, 2024 10:07:24 PM GMT+01:00, Jose Storopoli ***@***.***> wrote:
>We need to have a 23.11 release.
>

No disagreement here, it's getting overdue =(

**Comment by mrtnvgr** [comment]
[24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) was released

**Comment by taranarmo** [comment]
@mrtnvgr, I don't see `release-24.05` branch in the repo. I guess the release is being prepared now.
@t184256, do you need some help? I couldn't fine instructions on how to add a release here.

**Comment by mrtnvgr** [comment]
> @mrtnvgr, I don't see `release-24.05` branch in the repo. I guess the release is being prepared now.

Maybe I don't understand something right, but I've updated to it already 🤔 

![20240214_22h25m05s_grim](https://github.com/nix-community/nix-on-droid/assets/48406064/44fe1595-9595-4412-bb2f-ba5248177b27)

**Comment by Gerschtli** [comment]
@taranarmo You can have a look at https://github.com/nix-community/nix-on-droid/pull/267 for reference. It is mainly updating flake inputs and other stuff where we hardcoded the version, especially proot. We should definitely document the release process somewhere..

**Comment by Gerschtli** [comment]
> > @mrtnvgr, I don't see `release-24.05` branch in the repo. I guess the release is being prepared now.
> 
> Maybe I don't understand something right, but I've updated to it already 🤔

You are referring to the NixOS release, this issue is about nix-on-droid.

**Comment by t184256** [comment]
> @mrtnvgr, I don't see `release-24.05` branch in the repo. I guess the release is being prepared now. @t184256, do you need some help? I couldn't fine instructions on how to add a release here.

There's a github projects board, but first I need to overcome myself and test&merge outstanding merge requests. + there's also a nix-on-droid-app merge request to test.

**Comment by t184256** [comment]
https://github.com/nix-community/nix-on-droid/tree/release-23.11
