### ISSUE TITLE
Incompatibility with Tailscale MagicDns (Could not resolve host)

### ISSUE THREAD

**Issue by MinerSebas** [nix-community/nix-on-droid#322]
I am running tailscale on my Phone and when i try to access a server running tailscale, `curl` and `wget` are unable to resolve the hostname.
![Screenshot_20240128_213448_Nix](https://github.com/nix-community/nix-on-droid/assets/66798382/b4bf853e-3c0a-4d3b-a161-1c62a2da78a2)

Regular urls work correctly.

When using the browser or regular termux, the hostname can be resolved:
![Screenshot_20240128_212424_Termux](https://github.com/nix-community/nix-on-droid/assets/66798382/a5e9d8cf-af2e-452e-8f65-2efb37440537)

**Comment by MinerSebas** [comment]
Just noticed #2 which is probably the root cause, will investigate further.

**Comment by MinerSebas** [comment]
I fixed the hostname resolution after adding the Tailscale DNS Server to resolv.conf file, which fixed it for `wget`,
but `curl` does now neither print errors nor print contents.
![Screenshot_20240129_172820_Nix](https://github.com/nix-community/nix-on-droid/assets/66798382/ae0515d5-2e05-4078-b4ba-6342470177e1)

**Comment by matshch** [comment]
`curl` does not follow redirects by default, you need to add `-L` flag to it.

**Comment by MinerSebas** [comment]
Ah, my inexperience with curl shows, though I am still confused as to why it seemed to partially work without `-L` over in Termux.

Closing this Issue as all relevant issues are resolved.
