### ISSUE TITLE
Android security killing nix process

### ISSUE THREAD

**Issue by carbolymer** [nix-community/nix-on-droid#333]
Sometimes Android kills the nix process for the security reasons. Seems a bit random. For example, when running `nix profile list` five times, only one execution fails with:
```
bash-5.2$ nix profile list
Killed
```
And the following error pops out:
![Screenshot_2024-02-20-11-05-39-10_7c9fdf2472f91e6d21f35bb801178e75](https://github.com/nix-community/nix-on-droid/assets/228866/0a510c52-11c1-42db-87e0-8b768e7b4b44)

That's definitely a false positive from some security heuristics system. Any ideas where this comes from?
I haven't observed anything similar on Termux, so I don't if it's related to nix or Termux.

Android 14
OxygenOS 14.0

**Comment by t184256** [comment]
I don't know what is this mechanism.

**Comment by Gerschtli** [comment]
Looks like BitWarden does some stuff, not sure what exactly..

**Comment by carbolymer** [comment]
@Gerschtli that's just bitwarden autocompletion service saying that the vault is locked. I doubt it is making a difference here.

**Comment by carbolymer** [comment]
This one was odd. Turns out it's not a nix-on-droid bug, but it's an accessibility setting that's interfering somehow.

1. Go to Android Settings > Additional Settings > Accessibility > Accessibility Menu, set "Shortcut" to `Off`.
2. Go to Android Settings > Additional Settings > Accessibility > Downloaded apps, disable all, disable all, disable shortcuts for all of them.

After that, `nix profile` isn't killed by OS anymore.

**Comment by elkcl** [comment]
Getting the same problem right after installing the app when it tries to bootstrap Nix. Using Oxygen 14.0 (on Android 14) as well. Tried turning off all the accessibility shortcuts, but to no avail (they weren't turned on in the first place)

**Comment by t184256** [comment]
On July 20, 2024 1:06:12 AM GMT+03:00, Elk Cloner ***@***.***> wrote:
>Getting the same problem right after installing the app when it tries to bootstrap Nix. Using Oxygen 14.0 (on Android 14) as well. Tried turning off all the accessibility shortcuts, but to no avail (they weren't turned on in the first place)
>

Try "acquire wakelock" in the notification. https://dontkillmyapp.com is a good resource with per-vendor instructions, try that.

**Comment by elkcl** [comment]
I tried all that, even disabled killing of phantom processes as described [here](https://github.com/agnostic-apollo/Android-Docs/blob/master/en/docs/apps/processes/phantom-cached-and-empty-processes.md#commands-to-disable-phantom-process-killing-and-tldr), but it's still the same problem. It's not like it's getting killed because of battery-hogging, android thinks that the app is malicious for some reason.

![Screenshot_2024_07_20_01_18_55_59_7c9fdf2472f91e6d21f35bb801178e75](https://github.com/user-attachments/assets/720dd209-c77b-4d2c-8058-66e9c3044137)

**Comment by t184256** [comment]
I'm afraid you'd have to find and disable the heuristics. I don't think there's something to be done from my side, sorry...

The bootstrap is resource-intensive, maybe that's suspicious to it.

**Comment by carbolymer** [comment]
@elkcl My money is still on accessibility settings. Are you sure you have everything disabled in accessibility settings? Have you tried killing all background apps and restarting? I don't remember If I did that too.

**Comment by elkcl** [comment]
@carbolymer Yes, I've tried doing all that, and it still doesn't work. I've found out that other Oneplus 12 users on Oxygen OS 14 also have a similar problem, the security alert is triggered if you try to launch more than 40 processes under proot for some reason (it isn't triggered if not under proot, and turning off phantom process restrictions in the developer options also doesn't help) 

https://xdaforums.com/t/termux-processes-getting-flagged-as-malicious-software-and-killed.4660971/

https://community.oneplus.com/thread/1625392448551256065

**Comment by carbolymer** [comment]
nix-on-droid is dead on Oxygen OS 15: https://old.reddit.com/r/termux/comments/1gks9mf/announcement_termux_broken_on_android_15_for/

**Comment by elkcl** [comment]
Damn, that sucks. Thanks for the heads up, looks like I'm skipping this update for now
