### ISSUE TITLE
"Environment.pathsToLink does not exist" error.

### ISSUE THREAD

**Issue by yhanruzai** [nix-community/nix-on-droid#335]
I was trying to port my NixOS Dotfiles to Nix-on-droid [(here they are)](https://github.com/yhanruzai/broadsword). However, no matter what I do they don't work under nix-on-droid due to the same mistake.

Can anyone explain to me what is wrong with my setup or if it is just a bug? I'm new to Nix-on-droid and, honestly, to Nix in general.

**Comment by Gerschtli** [comment]
You should not load the nixosModule of home-manager into your nix-on-droid configuration. NixOS is not the same as nix-on-droid. Please read the readme regarding the correct home-manager Integration.

**Comment by yhanruzai** [comment]
Ah yes, I understand... is there any other way to pass it as a module like "nix-on-droidModules" or something like that? Because wittout it, Home Manager doesn't seem to be enabled. In the templates, it also doesn't appear in any other way but they still work somehow....

**Comment by Gerschtli** [comment]
Home manager does not expose a nix-on-droid module. The home-manager template contains everything that is needed to setup home-manager. That is the reason why we created this template ;)

You can have a look at `modules/home-manager.nix` to see the implementation.

**Comment by yhanruzai** [comment]
I see... I managed to get it working by that, thank you :) Although, Nix-on-droid seem to be lacking on some features for now (terminal colors) it is still an amazing project and I hope this project improves. God bless you :)
