### ISSUE TITLE
Insecure packages

### ISSUE THREAD

**Issue by RyanGibb** [nix-community/nix-on-droid#342]
I can't quite figure out how to allow the use of insecure packages without a shell variable.

When setting
```
nixpkgs.config.permittedInsecurePackages
```

I get
```
Failed assertions:
- In a flake setup, the options nixpkgs.* should not be
 used. Instead, rely on the provided flake outputs and pass in
 the necessary nixpkgs object
```

I'm using flakes. The full config can be found at
- https://github.com/RyanGibb/nixos/blob/948e1a4ea7be2658cf4e0beb0f1878fe1ded1889/flake.nix#L194
- https://github.com/RyanGibb/nixos/blob/948e1a4ea7be2658cf4e0beb0f1878fe1ded1889/nix-on-droid/default.nix

**Comment by Gerschtli** [comment]
You need to pass an instance of nixpkgs with your config applied to nixOnDroidConfiguration:


```nix
{
    nixOnDroidConfigurations.default = nix-on-droid.lib.nixOnDroidConfiguration {
      modules = [ ./nix-on-droid/default.nix ];
      pkgs = import nixpkgs { config.permittedInsecurePackages = ...; };
    };
}
```

**Comment by RyanGibb** [comment]
Thank you!
