### ISSUE TITLE
Changing hostname (for flakes)

### ISSUE THREAD

**Issue by jpentland** [nix-community/nix-on-droid#345]
Currently when running ```hostname``` we see the result ```localhost``` which is also used to locate the system target for ```nix-on-droid switch``` when using flakes.

It would be helpful to change this to allow several nix-on-droid devices to be included in the same flake. Of course there could be other workarounds such as aliasing the command, if not possible, but it would be nice if this were possible.

**Comment by jpentland** [comment]
Oops, missed that in search because of the space. The actual hostname of the device isn't 'localhost' though, so this has something to do with the chroot?

**Comment by mags-issues** [comment]
Consider closing this as a duplicate 🙏
