### ISSUE TITLE
Are there x86_64 bootstrap tars availible?

### ISSUE THREAD

**Issue by Quackdoc** [nix-community/nix-on-droid#352]
As the title says, are there any plans on making x86_64 tars available?

**Comment by t184256** [comment]
On May 1, 2024 11:23:41 AM GMT+02:00, Mitchel Stewart ***@***.***> wrote:
>As the title says, are there any plans on making x86_64 tars available?
>

Not really. I once added i686 on someone's request; then, years of building it with zero feedbacklater, it was dropped.

I don't have a device to test it, so I'm reluctant to support it. That isn't an outright "no" then: say, if you provide a GitHub CI action (they have KVM now) that tests it in an emulator, then why not.

**Comment by Quackdoc** [comment]
I see. I'll have to look into setting up the github CI, The two main ways to test it would be BlissOS or Waydroid. I would have to figure out setting up tests, but if I can I will make a PR

**Comment by t184256** [comment]
I've started looking into this. If you still want this for whatever your device was, please try out https://nix-on-droid.unboiled.info/bootstrap-emulator-powered-ci

**Comment by t184256** [comment]
(pre)release-24.05 now comes with first-class x86_64 support that's, arguably, better tested than aarch64.
