### ISSUE TITLE
Git support 

### ISSUE THREAD

**Issue by Greenarrow4245** [nix-community/nix-on-droid#354]
Can I install git same way as I do normally in termux pp a££

**Comment by Gerschtli** [comment]
No, in nix-on-droid you can either install it via the nix package manager or through adding it to your nix-on-droid.nix config and running `nix-on-droid switch`.

**Comment by Greenarrow4245** [comment]
> No, in nix-on-droid you can either install it via the nix package manager or through adding it to your nix-on-droid.nix config and running `nix-on-droid switch`.

،،no like setting it up

**Comment by Gerschtli** [comment]
Please be more specific what you want to achieve, then it is easier to help you :)

**Comment by Greenarrow4245** [comment]
> Please be more specific what you want to achieve, then it is easier to help you :)

Got for development on nix on droid

**Comment by Gerschtli** [comment]
See my comment here: https://github.com/nix-community/nix-on-droid/issues/355#issuecomment-2105007040

Git can be installed and configured through the usual config files like `~/.gitconfig`.
