### ISSUE TITLE
nix command

### ISSUE THREAD

**Issue by Greenarrow4245** [nix-community/nix-on-droid#356]
![Screenshot_20240511_165726_Nix.png](https://github.com/nix-community/nix-on-droid/assets/110173995/64afe3e8-071f-4411-91c3-1627c44a0dcb)

#355

**Comment by Greenarrow4245** [comment]
chstgpt said to use it after nix search

**Comment by Gerschtli** [comment]
See my comment https://github.com/nix-community/nix-on-droid/issues/355#issuecomment-2105675564
