### ISSUE TITLE
sourcing .bashrc crashes the app

### ISSUE THREAD

**Issue by Greenarrow4245** [nix-community/nix-on-droid#361]
when I source .bashrc the app crashes and doesn't let me in I had to delete the file through failsafe session

**Comment by Gerschtli** [comment]
Can you provide more details? What is your setup? What is the contents of your nix-on-droid.nix, your .bashrc? What shell are you running?

**Comment by Greenarrow4245** [comment]
> Can you provide more details? What is your setup? What is the contents of your nix-on-droid.nix, your .bashrc? What shell are you running?

fixed
