### ISSUE TITLE
Font change

### ISSUE THREAD

**Issue by Kazan20** [nix-community/nix-on-droid#363]
See I want to change the font to JetBrains mono but everytime I search for something nothing shows up so please help 

Nix-on-droid bootstrap aarch64 23.11

**Comment by t184256** [comment]
Define

> everytime I search for something nothing shows up

**Comment by Kazan20** [comment]
Like I mean I don't see any search results of people changing the font on nix-on-droid

**Comment by t184256** [comment]
Well, there's an [option](https://nix-community.github.io/nix-on-droid/nix-on-droid-options.html#opt-terminal.font) for changing the font, implemented in a [PR](https://github.com/nix-community/nix-on-droid/pull/201/files) filed as a response to an [issue](https://github.com/nix-community/nix-on-droid/issues/120).
