### ISSUE TITLE
upgrade to 24.05 break everything

### ISSUE THREAD

**Issue by pinage404** [nix-community/nix-on-droid#366]
Hello,

i tried to [upgrade nixpkgs from 23.11 to 24.11](https://gitlab.com/pinage404/dotfiles/-/commit/56339954f68e9688689bd3cf0142524a134f03ac)

direnv automatically reloaded the environnement

now, i can do nothing, typing on the keyboard does nothing

i tried to relaunch the app

i tried to start new terminals, but i always have the same message

![Screenshot_20240602-131434](https://github.com/nix-community/nix-on-droid/assets/6325757/15d95543-2f7b-4ad4-aa45-944ea2c74f06)
![Screenshot_20240602-131536](https://github.com/nix-community/nix-on-droid/assets/6325757/e7bd2534-ad20-4c81-8837-a31b401552fa)

How to fix it ?

Maybe i will reinstall the app

**Comment by Gerschtli** [comment]
It seems something regarding the login shell changed. Currently nix-on-droid is not tested/adapted for 24.05 yet.

As a quick fix, you can change the login-inner file mentioned in the error message via failsafe shell to point to the actual fish shell binary.

**Comment by pinage404** [comment]
`nano`, `vim` & `vi` seem not present

How to change the login-inner ?

![Screenshot_20240604-002930](https://github.com/nix-community/nix-on-droid/assets/6325757/9e358ed3-e0c5-4c17-ba43-85f7e5170430)

**Comment by taranarmo** [comment]
@pinage404, you need to create a failsafe session, probably you may follow instructions from [Termux wiki](https://wiki.termux.com/wiki/Recover_a_broken_environment)

**Comment by pinage404** [comment]
i managed to open a failsafe session

without `vim` nor `nano`, i couldn't find a way to repair the file

i didn't want to (re)move a file that i don't know how it is generated / managed, because i don't know how fix afterwards

i removed all the data of the app then reinstalled the app
