### ISSUE TITLE
nix command

### ISSUE THREAD

**Issue by Greenarrow4245** [nix-community/nix-on-droid#367]
![Screenshot_20240602_200128_Nix.png](https://github.com/nix-community/nix-on-droid/assets/110173995/54d880ec-d268-4cf9-b735-b993a1941d25)
enabling one feature doesnt work and in .bashrc I have nix command no work

**Comment by t184256** [comment]
This is a bugtracker for nix-on-droid itself, not a general support forum. Consider using [discussions](https://github.com/nix-community/nix-on-droid/discussions) for that.

As for the report itself, cannot reproduce; `nix --extra-experimental-features "nix-command flakes" search nixpkgs gnumake` works for me. The error is indicative of nix installed in multi-user mode not finding a daemon, and I can't fathom how you achieved that. If you also don't know what you did, just start anew.
