### ISSUE TITLE
Audited Resource, Min severity: Info

### ISSUE THREAD

**Issue by SystemWar** [nix-community/nix-on-droid#376]
Take a look at the logs for Audited Resource (minimum severity: Info) in project lustrous-setup-418310: https://console.cloud.google.com/logs?advancedFilter=resource.type%3D%22audited_resource%22%20AND%20severity%3E%3DNOTICE%20AND%20timestamp%3E%3D%222024-06-11T17%3A04%3A43.989%2B02%3A00%22%20AND%20timestamp%3C%3D%222024-06-11T17%3A04%3A43.990%2B02%3A00%22&project=lustrous-setup-418310&src=VESPA

**Comment by Gerschtli** [comment]
Please stop spamming unrelated things in the nix-on-droid issues.
