### ISSUE TITLE
Home-Manager Version Mismatch Error with Flakes

### ISSUE THREAD

**Issue by CaptainLexington** [nix-community/nix-on-droid#380]
With a fresh install of 23.11, adding home-manager as a source **pinned at release-23.11**, building with `home.nix` and `home.stateVersion = 23.11` produces the following output: 

```shell
bash-5.2$ nix-on-droid switch --flake .
Building activation package...
trace: warning: You are using

  Home Manager version 24.05 and
  Nixpkgs version 23.11.

Using mismatched versions is likely to cause errors and unexpected
behavior. It is therefore highly recommended to use a release of Home
Manager that corresponds with your chosen release of Nixpkgs.
```

**Comment by Gerschtli** [comment]
Please post your flake.nix file in order to allow me to help you debug :)

**Comment by CaptainLexington** [comment]
Sorry about a looong delay! Unfortunately I decided to go back to using Termux for now. I'll close this. Thank you!
