### ISSUE TITLE
24.05

### ISSUE THREAD

**Issue by Sepero** [nix-community/nix-on-droid#381]
What needs to be done to get 24.05?

**Comment by t184256** [comment]
[Several things](https://github.com/nix-community/nix-on-droid/pull/372#issuecomment-2150525158), help is welcome.

**Comment by t184256** [comment]
And if you meant "what needs to be done to get nixpkgs 24.05", then just install 23.11, switch channels or flake inputs to nixpkgs 24.05 and update. It's not tested by me yet, but it should work.

**Comment by Sepero** [comment]
> just install 23.11, switch channels or flake inputs to nixpkgs 24.05 and update. It's not tested by me yet, but it should work.

I'm confused, because this is exactly what I did and found out 24.05 doesn't exist? Perhaps you meant testing branch? I appreciate everything you're doing on this project.

https://github.com/nix-community/nix-on-droid/tree/release-23.11

https://github.com/nix-community/nix-on-droid/tree/release-24.05

**Comment by t184256** [comment]
>> switch channels or flake inputs to nixpkgs 24.05
>
> this is exactly what I did and found out 24.05 doesn't exist?

Yes, the branch doesn't exist yet. "Switch channels or flake inputs to 24.05 for everything but nix-on-droid", that is. Could be nixpkgs (named nixpkgs or nixos), could be home-manager or something else you might be using. Basically, proceed with upgrading everything, but hold nix-on-droid back.

**Comment by t184256** [comment]
release-24.05 is here. Make sure to check out the new android-integration options.

**Comment by 573** [comment]
Wow, this is absolutely mind-blowing what you achieved here, emulator tests, android system integration, only to name a few.

Can't wait to update my flake, thank you to all involved !
