### ISSUE TITLE
README is outdated with 24.05 ?

### ISSUE THREAD

**Issue by pinage404** [nix-community/nix-on-droid#386]
Hi,

The README seems outdated compared to template

https://github.com/nix-community/nix-on-droid/blob/8bcadcef69dcb5ca177bfb6ea3dc6b092cda2b06/README.md?plain=1#L195

https://github.com/nix-community/nix-on-droid/blob/8bcadcef69dcb5ca177bfb6ea3dc6b092cda2b06/templates/minimal/flake.nix#L16

**Comment by t184256** [comment]
Thanks for spotting that! Seems like I've updated it, but wrong.
