### ISSUE TITLE
styling app not found

### ISSUE THREAD

**Issue by teacupmaps** [nix-community/nix-on-droid#390]
![Screenshot_20240719-180224_Nix](https://github.com/user-attachments/assets/3dfd5396-5981-4fa0-b26f-380a8eae4af5)

this opens https://f-droid.org/en/packages/com.termux.nix.styling, which doesn't exist

**Comment by t184256** [comment]
You don't need one, everything is configured as everything else in nix-on-droid: through the Nix config: https://nix-community.github.io/nix-on-droid/nix-on-droid-options.html#opt-terminal.colors

The button is misleading indeed; if you want to remove it, file a PR against https://github.com/nix-community/nix-on-droid-app
