### ISSUE TITLE
Is it possible to use packages from different channel in nix-on-droid.nix

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [nix-community/nix-on-droid#392]
I added the nix unstable channel, because I want neovim 0.10.
But how can I add packages from a different channel in `nix-on-droid.nix`?

**Comment by t184256** [comment]
On July 24, 2024 7:30:03 AM GMT+03:00, Nathan ***@***.***> wrote:
>I added the nix unstable channel, because I want neovim 0.10.
>But how can I add packages from a different channel in `nix-on-droid.nix`?
>

`(import <channel-name-you-added-it-as> { }).neovim`?

**Comment by RudolfVonKrugstein** [comment]
yes, thank you! Also found the documentation from Home-Manager, which might help someone else: https://nix-community.github.io/home-manager/index.xhtml#_how_do_i_install_packages_from_nixpkgs_unstable
