### ISSUE TITLE
What is the best way to enable bash completion on nix-on-droid?

### ISSUE THREAD

**Issue by SpidFightFR** [nix-community/nix-on-droid#395]
I tried to setup `programs.bash.enableCompletion = true;` but the option isn't available (i guess it's a nixos thing, not nix). 

Which way would you guys advise me to enable these? Am I missing something?

**Comment by t184256** [comment]
With a home-manager option: https://nix-community.github.io/home-manager/options.xhtml#opt-programs.bash.enableCompletion

This has to go into home-manager section of the config. Non-flakes: default config should have instructions on how to enable it. Flakes: there's a template in this repository with an example of how to enable it.

**Comment by SpidFightFR** [comment]
> With a home-manager option: https://nix-community.github.io/home-manager/options.xhtml#opt-programs.bash.enableCompletion This has to go into home-manager section of the config. Non-flakes: default config should have instructions on how to enable it. Flakes: there's a template in this repository with an example of how to enable it.

i got some issues with home manager, i tried to enable it but it says that the [nix-on-droid flake i'm using](https://github.com/SpidFightFR/nix-on-droid/tree/home-mgr), it seems my environment is conflicting or something, the error is weird on it's own, it says a package is conflicting, and that i should run `nix-env -q` when i do so, it prints `nix-on-droid-path` and that's about it... what could that be linked to ?

(My home manager config only has a bash.nix file imported, with the lines available in the link you posted above. did that happened to you as well ? Am i missing something here ?)

**Comment by t184256** [comment]
Hard to say with neither the config you're using (one you've linked to does not have a bash.nix) nor the error message (retelling error messages isn't a great idea overall). Sounds like you have a package installed with several methods at once. Also, using nix-env is pretty much never a good idea.

**Comment by SpidFightFR** [comment]
> Hard to say with neither the config you're using (one you've linked to does not have a bash.nix) nor the error message (retelling error messages isn't a great idea overall). Sounds like you have a package installed with several methods at once. Also, using nix-env is pretty much never a good idea.

My apologies, i completely forgot to link the files.

here is my home-manager repo:
https://github.com/SpidFightFR/home-manager-android

**Comment by SpidFightFR** [comment]
this one contains the bash.nix.

**Comment by t184256** [comment]
This one doesn't define a nix-on-droid configuration (see [template](https://github.com/nix-community/nix-on-droid/tree/master/templates/home-manager) for the example), so I'm not sure how are you applying it. Please share the full reproducer. If you have installed home-manager separately (1st set of packages) and are applying it on top of a regular environment (2nd set of packages) where you've also installed something using nix-env (3rd set of packages), then I'm not very surprised you've got some conflicts.

**Comment by SpidFightFR** [comment]
> This one doesn't define a nix-on-droid configuration (see [template](https://github.com/nix-community/nix-on-droid/tree/master/templates/home-manager) for the example), so I'm not sure how are you applying it. Please share the full reproducer. If you have installed home-manager separately (1st set of packages) and are applying it on top of a regular environment (2nd set of packages) where you've also installed something using nix-env (3rd set of packages), then I'm not very surprised you've got some conflicts.

ngl I think my whole thing is basically trash... Went in too many directions at once, it's a huge mess.
I'll try to refactor the `home-mgr` branch of my nix-on-droid flake, in order to include home manager, hopefully it will work better.

I'll be right back. thanks for your help

**Comment by SpidFightFR** [comment]
hey again @t184256, sorry for the ping. I made a slight refactor of the home-mgr branch, leading to the deletion of my home-manager repo (useless after what i did on my main `nix-on-droid` config repo).

After running `nix-on-droid switch --flake .` it seems like it also applied the home-manager config, is it the case ?

**Comment by t184256** [comment]
Yeah, that was the idea, one switch for everything.

**Comment by SpidFightFR** [comment]
> Yeah, that was the idea, one switch for everything.

Alright, welp imma play a bit with that and see what i can do with it. closing this issue. Thank you man, i appreciate your help (note: i started to learn about flakes 4 days ago lol, i'm still a huge noob with those) :sweat_smile:
