### ISSUE TITLE
ninix-instantiate --eval issue but works fine in nix repl

### ISSUE THREAD

**Issue by Greenarrow4245** [nix-community/nix-on-droid#397]
![Screenshot_20240730_184853_Nix.png](https://github.com/user-attachments/assets/db2ee241-c28e-4936-bfa5-d88e9a36b1c6)

**Comment by Gerschtli** [comment]
We do not provide support for the underlying tooling. Please consult the official docs.

https://nix.dev/manual/nix/2.22/command-ref/nix-instantiate
