### ISSUE TITLE
accidentally removed resolve confab nd I recreated it nix-env works fine but it doesn't have the color

### ISSUE THREAD

**Issue by Greenarrow4245** [nix-community/nix-on-droid#399]
![Screenshot_20240801_134907_Nix.png](https://github.com/user-attachments/assets/399cda02-da11-47f7-af56-78789d4d3a0e)

**Comment by Greenarrow4245** [comment]
it's resolv.conf sorry typo

**Comment by Gerschtli** [comment]
please run nix-on-droid switch as usual :)
