### ISSUE TITLE
Unable no build second profile generation: hard link error

### ISSUE THREAD

**Issue by bemyak** [nix-community/nix-on-droid#401]
Hello!

I'm trying to set up nix-on-droid on my Fairphone 5, running the official Android 14, no root.
The bootstrapping and initialization work fine, even though it takes quite some time.
The very first building of [my nix flake](https://codeberg.org/bemyak/nix) also succeeds.
Subsequent builds without any changes also succeed.

However, when I then try to either enter the development shell (with `nix develop`) or make some trivial change (e.g., commenting out an installed package), the build fails immediately with a similar error:
```bash
❯ nix-on-droid switch --flake '.#fp5'
Building activation package...
error: filesystem error: cannot create hard link: Operation not permitted [/nix/store/mqz5ki4wsa86a7zxgcqrl9xf1kkfbhja-source/.envrc] [/nix/store/.links/1a7ig9z32cxraskfnq7qnlq0096rv8l12a20jv6dzsfxj6z60w1q]
```

The paths to nix store vary depending on the change I've made. I assume it's just the first derivation it tries to evaluate.

Some more details:
* Nix-on-droid app version: `0.118.0_v0.3.6_nix` from F-Droid
* Android 14
* Bootstrapped from:`https://nix-on-droid.unboiled.info/bootstrap-release-24.05/`
* Kernel version `5.4.242-qgki-g5d59c34fa0ec`
* Build number `FP5.UT20.B.041.20240624`
* Nix version: `2.23.3`
* File system used for /nix:
  ```bash
  $ stat -f -c %T /nix
  f2fs
  ```
* Flake: https://codeberg.org/bemyak/nix/src/branch/main/flake.nix

**Comment by Gerschtli** [comment]
You enable auto optimise store https://codeberg.org/bemyak/nix/src/commit/11468f78e7c958fa9433d15da550691317f07a98/home/common/nix.nix#L5. Hard links don't seem to work within nix-on-droid AFAIK. Maybe @t184256 has an explanation to why this is the case, but for now just disable this option. (Needs probably a complete re-installation for you because there are now hard links present in your /nix/store)

**Comment by bemyak** [comment]
I've tried disabling this option, but I haven't done full re-installation after that.
Thanks, I'll try!
