### ISSUE TITLE
nix flake init create x86_64 but iam on aarch64

### ISSUE THREAD

**Issue by Greenarrow4245** [nix-community/nix-on-droid#407]
![Screenshot_20240815_230322_Nix.png](https://github.com/user-attachments/assets/d14dedcf-6514-45c8-ba82-07868ed9706d)

**Comment by Gerschtli** [comment]
nix flake init copies just files. The template you used contains exactly this content.

This is also not a nix-on-droid issue because this template is defined outside of our project.
