### ISSUE TITLE
nix-shell hangs if I try to pin nixpkgs

### ISSUE THREAD

**Issue by switch-to-gitlab** [nix-community/nix-on-droid#417]
Hello, 

I am unable to pin to any kind of channel or commit etc.

For example, given

```nix
let
  nixpkgs = fetchTarball "https://github.com/NixOS/nixpkgs/tarball/nixos-24.05";
  pkgs = import nixpkgs { config = {}; overlays = []; };
in
pkgs.mkShellNoCC {
  packages = with pkgs; [
    cowsay
    lolcat
  ];
}
```

If I run `nix-shell` or `nix-shell --pure` the terminal just hangs indefinitely with no output. If I replace the pin with `<nixpkgs>` it works fine.

I am on a Moto G Power 5G 2023 on a fairly clean installation. The only modification I've made to the root config is to add emacs to the packages.

Thank you for your work on this project. I really enjoy it.

**Comment by Gerschtli** [comment]
This can take a while (some minutes until an hour, depending on your device) if you are downloading a new version of nixpkgs. Please try to start it again and watch the used storage of the app. If it grows that it is working.

You can expect similar times compared to the initial installation of nix-on-droid.

**Comment by switch-to-gitlab** [comment]
@Gerschtli Oh NO you're right that was it. What a n00b. What an absolute end user 😳🫣😶‍🌫️

Thank you for your help lol!
